version: "3"

volumes:
  polyfill-buffer:
    driver: juicedata/juicefs
    driver_opts:
      name: polyfill-buffer
      metaurl: sqlite3://polyfill-buffer.db
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

services:
  api-service:
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3000
    volumes:
      - polyfill-buffer:/tmp/@wessberg/polyfiller
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
