version: "3"

volumes:
  polyfill-cache:
    driver: juicedata/juicefs
    driver_opts:
      name: polyfill-cache
      # metaurl: sqlite3://polyfill-cache.db
      metaurl: postgres://postgres:${ADMIN_JWT_SECRET}@postgres-server:5432/juicefs
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

networks:
  polyfiller:

services:
  api-service:
    depends_on:
      - postgres-server
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - polyfill-cache:/tmp/@wessberg/polyfiller
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
  
  postgres-server:
    image: postgres:14.11
    environment:
      - POSTGRES_PASSWORD=${ADMIN_JWT_SECRET}
    volumes:
      - polyfill-cache:/var/lib/postgresql/data/
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      retries: 5
    labels:
      - autoheal=true
    restart: always

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  caddy:
    depends_on:
      - api-service
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - polyfiller
    restart: always
    command: caddy reverse-proxy --from polyfiller.app --to api-service:3000
