version: '3'

volumes:
  polyfill-cache:
    driver: juicedata/juicefs
    driver_opts:
      name: polyfill-cache
      metaurl: sqlite3://polyfill-cache.db
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

services:
    api-service:
        image: polyfiller/api-service
        environment:
            - NODE_ENV=production
        ports:
            - 3001:3000
        volumes:
            - polyfill-cache:/tmp/@wessberg/polyfiller
        restart: always
