version: "3"
volumes:
  metadata:
    driver: local

networks:
  polyfiller:

services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  rclone:
    image: rclone/rclone:latest
    container_name: rclone_container
    cap_add:
      - SYS_ADMIN # Necessary for FUSE
      - MKNOD # Necessary for FUSE
    devices:
      - "/dev/fuse" # Necessary for FUSE
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - ./config/rclone:/config/rclone # Mount the local rclone config directory to the container
      - ./metadata:/metadata:shared # Mount the local directory for the rclone mount
    command: "mount azure:/ /metadata --allow-other --allow-non-empty --vfs-cache-mode writes"
    restart: always
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf # Path to the rclone config file inside the container

  api-service:
    depends_on:
      - autoheal
      - rclone
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    volumes:
      - metadata:/tmp/@wessberg/polyfiller
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m

  caddy:
    depends_on:
      - api-service
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - polyfiller
    restart: always
    command: caddy reverse-proxy --from polyfiller.app --to api-service:3000
