version: "3"
networks:
  polyfiller:

services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  myjfs_format:
    image: juicedata/mount:latest
    command: juicefs format --storage wasb --bucket   ${BUCKET} --access-key=${ACCESS_KEY}  --secret-key=${SECRET_KEY}   redis://meta-server myjfs
    devices:
      - /dev/fuse
    networks:
      - polyfiller

  myjfs:
    image: juicedata/mount:latest
    privileged: true
    command: juicefs mount redis://meta-server myjfs /mnt
    volumes:
      - /mnt
    networks:
      - polyfiller
    

  meta-server:
    depends_on:
      - autoheal
    image: redislabs/redismod
    ports:
      - "6379:6379"
    networks:
      - polyfiller

    labels:
      - autoheal=true
    restart: always

  api-service:
    depends_on:
      - autoheal
      - meta-server
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    volumes:
      - /mnt:/tmp/@wessberg/polyfiller
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m

  caddy:
    depends_on:
      - api-service
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - polyfiller
    restart: always
    command: caddy reverse-proxy --from polyfiller.app --to api-service:3000
