name: "Deploy"

on:
  push:
    branches:
      - master
  release:
    types: ["published"]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: NODE_ENV=production npm run build

      - name: Deploy
        run: node deploy.js
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER_NAME: ${{ secrets.DEPLOY_USER_NAME }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_DOMAIN_NAMES: ${{ secrets.DEPLOY_DOMAIN_NAMES }}
